version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

linters:
  disable:
    # Disable overly opinionated or noisy linters
    - depguard          # Too restrictive on imports in main package
    - exhaustruct       # Requires all struct fields initialized (too strict)
    - paralleltest      # Requires t.Parallel in all tests (not always appropriate)
    - testpackage       # Requires separate _test packages (stylistic)
    - varnamelen        # Too opinionated on variable name lengths
    - wrapcheck         # Too strict on error wrapping
    - err113            # Too strict on error creation
    - godox            # Complains about TODO/FIXME (we want those)
    - ireturn          # Too opinionated on interface returns
    - nonamedreturns    # Named returns are useful
    - nilnil           # Returning nil, nil is sometimes appropriate
    - gochecknoglobals  # Global variables are sometimes necessary
    - forbidigo         # May block useful functions
    - noinlineerr       # Inline error handling is often fine
    - nlreturn          # Too many whitespace opinions
    - wsl_v5            # Too many whitespace opinions
    - tagliatelle       # Too opinionated on struct tag naming
    - funcorder         # Function ordering is stylistic
    - interfacebloat    # Context dependent
  enable:
    # Enable all remaining available linters
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - zerologlint
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    gocyclo:
      min-complexity: 15
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false

formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(djalgorhythm)
    goimports:
      local-prefixes: [djalgorhythm]

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
