version: 2

project_name: djalgorhythm

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: djalgorhythm
    main: ./cmd/djalgorhythm
    binary: djalgorhythm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    flags:
      - -trimpath

archives:
  - id: djalgorhythm
    formats:
      - tar.gz
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - .env.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

dockers_v2:
  - id: djalgorhythm-images
    images:
      - enteee/djalgorhythm
      - ghcr.io/enteee/djalgorhythm
    dockerfile: Dockerfile
    ids:
      - djalgorhythm
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{ if not .IsSnapshot }}{{ .Tag }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}{{ end }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.description": "DJAlgoRhythm - Live Chat → Spotify DJ"
    flags:
      - "--pull"
      - "--push"
      - "--cache-from=type=gha"
      - "--cache-to=type=gha,mode=max"
      - "--provenance=false"

release:
  github:
    owner: Enteee
    name: DJAlgoRhythm
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## DJAlgoRhythm {{ .Tag }} Release 🎵

    This release includes the following changes:

  footer: |
    ## Installation

    ### Binary Download
    Download the appropriate binary for your platform from the assets below.

    ### Docker
    ```bash
    docker pull enteee/djalgorhythm:{{ .Tag }}
    ```

    ### Go Install
    ```bash
    go install github.com/Enteee/DJAlgoRhythm/cmd/djalgorhythm@{{ .Tag }}
    ```

    ## Checksums
    All binary checksums are available in `checksums.txt`.

    ---
    **Full Changelog**: https://github.com/Enteee/DJAlgoRhythm/compare/{{ .PreviousTag }}...{{ .Tag }}
