version: 2

project_name: djalgorhythm

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: djalgorhythm
    main: ./cmd/djalgorhythm
    binary: djalgorhythm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    flags:
      - -trimpath

archives:
  - id: djalgorhythm
    formats:
      - tar.gz
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - .env.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

docker_manifests:
  - name_template: "enteee/djalgorhythm:{{ .Tag }}"
    image_templates:
      - "enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "enteee/djalgorhythm:{{ .Tag }}-arm64"
  - name_template: "enteee/djalgorhythm:v{{ .Major }}"
    image_templates:
      - "enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "enteee/djalgorhythm:{{ .Tag }}-arm64"
  - name_template: "enteee/djalgorhythm:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "enteee/djalgorhythm:{{ .Tag }}-arm64"
  - name_template: "enteee/djalgorhythm:latest"
    image_templates:
      - "enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "enteee/djalgorhythm:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/enteee/djalgorhythm:{{ .Tag }}"
    image_templates:
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/enteee/djalgorhythm:v{{ .Major }}"
    image_templates:
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/enteee/djalgorhythm:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/enteee/djalgorhythm:latest"
    image_templates:
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-arm64"

dockers:
  # Multi-platform images for releases and main branch (always pushed)
  - image_templates:
      - "enteee/djalgorhythm:{{ .Tag }}-amd64"
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    ids:
      - djalgorhythm
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
      - "--cache-from=type=gha"
      - "--cache-to=type=gha,mode=max"
      - "--provenance=false"
  - image_templates:
      - "enteee/djalgorhythm:{{ .Tag }}-arm64"
      - "ghcr.io/enteee/djalgorhythm:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    ids:
      - djalgorhythm
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
      - "--cache-from=type=gha"
      - "--cache-to=type=gha,mode=max"
      - "--provenance=false"

release:
  github:
    owner: Enteee
    name: DJAlgoRhythm
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## DJAlgoRhythm {{ .Tag }} Release 🎵

    This release includes the following changes:

  footer: |
    ## Installation

    ### Binary Download
    Download the appropriate binary for your platform from the assets below.

    ### Docker
    ```bash
    docker pull enteee/djalgorhythm:{{ .Tag }}
    ```

    ### Go Install
    ```bash
    go install github.com/Enteee/DJAlgoRhythm/cmd/djalgorhythm@{{ .Tag }}
    ```

    ## Checksums
    All binary checksums are available in `checksums.txt`.

    ---
    **Full Changelog**: https://github.com/Enteee/DJAlgoRhythm/compare/{{ .PreviousTag }}...{{ .Tag }}
